[package]
name = "Liquidswap"
version = "0.4.1"
upgrade_policy = "immutable"

[addresses]
liquidswap = "0xdcf3f5381c94de140d2bdf597e200cbfb3ac4ebcb7abd718e406a2d473c5de88"

# Admins
dao_admin = "0xa5dd9f5abfac2da1e0eb3f67e3d09ed97710358e03a6e73bd66f4444f176b975"
emergency_admin = "0xa5dd9f5abfac2da1e0eb3f67e3d09ed97710358e03a6e73bd66f4444f176b975"
fee_admin = "0xa5dd9f5abfac2da1e0eb3f67e3d09ed97710358e03a6e73bd66f4444f176b975"

# Resource accounts: should be the same as @liquidswap_lp in lp_coin
liquidswap_pool_account = "0x1791d86161d0536c8b96bee45f1ddcda50145c438a9acc7447cff3de1e8692d6"
liquidswap_emergency_account = "0xadecf1fb0d7d2ab8aeaed7cf4480fe073e086ab105350dd866ed61baf5ebf2a5"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"

test_lp_owner = "0x12"

[dependencies.LiquidswapLP]
local = "./liquidswap_lp/"

[dependencies.LiquidswapInit]
local = "./liquidswap_init/"

[dependencies.AptosFramework]
local = "../aptos-core/aptos-move/framework/aptos-framework/"
