[package]
name = 'LiquidswapLP'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
liquidswap_lp = "0x1791d86161d0536c8b96bee45f1ddcda50145c438a9acc7447cff3de1e8692d6"

[dev-dependencies.MoveStdlib]
local = "../../aptos-core/aptos-move/framework/move-stdlib"
